name: Create live branch pull request

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches: [live, master]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  createLivePR:
    name: Create live branch pull request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Replace Text by LiveText
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Text\([[:space:]]\|<\|\/\|,\)/\1LiveText\2/g' {} +

      - name: Replace Markdown by LiveMarkdown
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Markdown\([[:space:]]\|<\|\/\|,\)/\1LiveMarkdown\2/g' {} +

      - name: Replace Image by LiveImage
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Image\([[:space:]]\|<\|\/\|,\)/\1LiveImage\2/g' {} +

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          branch: new-live-branch
          title: "Update live branch"
          base: live
