name: Update Live

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Replace Text by LiveText
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Text\([[:space:]]\|<\|\/\|,\)/\1LiveText\2/g' {} +

      - name: Replace Markdown by LiveMarkdown
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Markdown\([[:space:]]\|<\|\/\|,\)/\1LiveMarkdown\2/g' {} +

      - name: Replace Image by LiveImage
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Image\([[:space:]]\|<\|\/\|,\)/\1LiveImage\2/g' {} +

      - name: Replace Schedule by LiveSchedule
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Schedule\([[:space:]]\|<\|\/\|,\)/\1LiveSchedule\2/g' {} +

      - name: Replace Geolocation by LiveGeolocation
        run: find . -type f -name '*.astro' -exec sed -i 's/\([[:space:]]\|<\|\/\)Geolocation\([[:space:]]\|<\|\/\|,\)/\1LiveGeolocation\2/g' {} +

      - name: Push changes to version branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b live
          git add -A
          git commit -m "Bump live version"
          git push origin live --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}